name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "3609356"
